# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170310_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vendor_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whirlwind_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
