# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170315_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whirlwind_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
