# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whirlwind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whirlwind.Employees')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whirlwind.Vendor')),
            ],
            options={
                'db_table': 'AP Vendor Invoice',
                'managed': True,
            },
        ),
    ]
